# Observed symbols (perpetuals)
XSTOCK_ENABLED = True  # ← CHANGED — Phase 3: 72h paper validation started 2026-04-22
SPREAD_MAX_PCT = 0.003  # ← NEW

CRYPTO_SYMBOLS = ["BTCUSD", "ETHUSD", "SOLUSD", "BNBUSD"]

XSTOCK_SYMBOLS = [
    "GOOGLXUSD", "METAXUSD", "AAPLXUSD", "AMZNXUSD",
    "TSLAXUSD",  "NVDAXUSD", "COINXUSD", "CRCLXUSD",
    "QQQXUSD",   "SPYXUSD",
]

ACTIVE_SYMBOLS = CRYPTO_SYMBOLS + (XSTOCK_SYMBOLS if XSTOCK_ENABLED else [])
SYMBOLS = ACTIVE_SYMBOLS

# Loop cadence
DECISION_LOOP_SLEEP_SECONDS = 60
